insert into users (phone_number, user_name, user_type, email, password, enabled,
                   role_id, theme_id, geolocation_id,
                   registration_date, photo, reset_password_token) values
    ('222', 'Микеланджело Буанаротти', 'SPECIALIST', '', '$2a$12$a72Udagvfj0P2ezcWE1yV.s7mMxn6SgJsyHWVOMegNmTN/WBayFbC', true,
     1, 1, 1, now(), 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Miguel_Ángel%2C_por_Daniele_da_Volterra_%28detalle%29.jpg/1036px-Miguel_Ángel%2C_por_Daniele_da_Volterra_%28detalle%29.jpg',
     null),
    ('223', 'Дед Мороз', 'SPECIALIST', '', '$2a$12$a72Udagvfj0P2ezcWE1yV.s7mMxn6SgJsyHWVOMegNmTN/WBayFbC', true,
     1, 1, 1, now(), 'https://upload.wikimedia.org/wikipedia/commons/5/59/Ded_Moroz.jpg', null),
    ('224', 'Бакыт Бакытов', 'SPECIALIST', '', '$2a$12$a72Udagvfj0P2ezcWE1yV.s7mMxn6SgJsyHWVOMegNmTN/WBayFbC', true,
     1, 1, 1, now(), 'https://www.spectator.co.uk/wp-content/uploads/2021/01/Charles-Yu-©-Tina-Chiou._r1.jpg', null),
    ('225', 'Роза К.', 'CUSTOMER', '', '$2a$12$a72Udagvfj0P2ezcWE1yV.s7mMxn6SgJsyHWVOMegNmTN/WBayFbC', true,
     2, 1, 1, now(), 'https://images-s.kinorium.com/persona/300/215.jpg', null);

insert into specialists (user_id, company_name) values
((select id from users where user_name = 'Микеланджело Буанаротти'), 'Art Studio Michelangelo'),
((select id from users where user_name = 'Дед Мороз'), 'Дед Мороз и Ко'),
((select id from users where user_name = 'Бакыт Бакытов'), 'Gaming Dev');

insert into specialists_authorities (specialist_id, authority_id, date_start, date_end) values
((select id from specialists where company_name = 'Art Studio Michelangelo'), 1, now(), '2024-01-04 00:00:00.000000'),
((select id from specialists where company_name = 'Дед Мороз и Ко'), 1, now(), '2024-01-04 00:00:00.000000'),
((select id from specialists where company_name = 'Gaming Dev'), 1, now(), '2024-01-04 00:00:00.000000');


insert into resumes (specialist_id, name, resume_description, category_id, time_of_resume)
values ((select id from specialists where company_name = 'Art Studio Michelangelo'), 'Изготовление скульптур на заказ',
        'Изготовление скульптур любой сложности из мрамора, большой опыт и отличные рекомендации',
        (select id from categories where category_name = 'Разное'), now()),
       ((select id from specialists where company_name = 'Art Studio Michelangelo'), 'Изготовление картин и фресок на заказ',
        'Рисую картины и фрески в стиле Ренессанс любой сложности', (select id from categories where category_name = 'Разное'), now()),
    ((select id from specialists where company_name = 'Дед Мороз и Ко'), 'Ведущий праздников', 'Ведущий праздников для детей и взрослых',
     (select id from categories where category_name = 'Досуг'), now()),
       ((select id from specialists where company_name = 'Gaming Dev'), 'Разработка игр', 'Опытный разработчик игр',
        (select id from categories where category_name = 'Интернет-услуги'), now());

insert into portfolios (specialist_id, title, time_of_portfolio)
values ((select id from specialists where company_name = 'Art Studio Michelangelo'), 'Изготовление скульптур на заказ', now()),
        ((select id from specialists where company_name = 'Art Studio Michelangelo'), 'Изготовление картин и фресок на заказ', now()),
        ((select id from specialists where company_name = 'Дед Мороз и Ко'), 'Новогодник праздники с Дед Морозом', now()),
       ((select id from specialists where company_name = 'Gaming Dev'), 'Разработанные игры', now());


insert into photos (portfolio_id, photo_link, time_of_saving_photo)
values ((select id from portfolios where title = 'Изготовление скульптур на заказ'),
        'https://upload.wikimedia.org/wikipedia/commons/a/a0/%27David%27_by_Michelangelo_Fir_JBU002.jpg', now()),
       ((select id from portfolios where title = 'Изготовление скульптур на заказ'),
        'https://upload.wikimedia.org/wikipedia/commons/1/1f/Michelangelo%27s_Pieta_5450_cropncleaned_edit.jpg', now()),
       ((select id from portfolios where title = 'Изготовление скульптур на заказ'),
        'https://upload.wikimedia.org/wikipedia/commons/5/59/Michelangelo%27s_Moses_%28Rome%29.jpg', now()),
       ((select id from portfolios where title = 'Изготовление скульптур на заказ'),
        'https://upload.wikimedia.org/wikipedia/commons/b/b2/Buonarotti-scala.jpg', now()),
       ((select id from portfolios where title = 'Изготовление скульптур на заказ'),
        'https://upload.wikimedia.org/wikipedia/commons/4/49/Michelangelo_Brutus.jpg', now()),
    ((select id from portfolios where title = 'Изготовление картин и фресок на заказ'),
    'https://upload.wikimedia.org/wikipedia/commons/7/73/God2-Sistine_Chapel.png', now()),
       ((select id from portfolios where title = 'Изготовление картин и фресок на заказ'),
        'https://upload.wikimedia.org/wikipedia/commons/1/18/Last_Judgement_%28Michelangelo%29.jpg', now()),
    ((select id from portfolios where title = 'Новогодник праздники с Дед Морозом'), 'https://dobroman.ru/wp-content/uploads/2019/09/5645454_2.jpg', now()),
       ((select id from portfolios where title = 'Новогодник праздники с Дед Морозом'), 'https://regions.kidsreview.ru/sites/default/files/styles/oww/public/10/18/2017_-_1616/m1li5rh_kre.jpg', now()),
       ((select id from portfolios where title = 'Разработанные игры'), 'https://image.api.playstation.com/vulcan/img/cfn/11307uYG0CXzRuA9aryByTHYrQLFz-HVQ3VVl7aAysxK15HMpqjkAIcC_R5vdfZt52hAXQNHoYhSuoSq_46_MT_tDBcLu49I.png', now()),
       ((select id from portfolios where title = 'Разработанные игры'), 'https://assetsio.reedpopcdn.com/Dota-Going-On-An-Adventure-.jpg', now()),
       ((select id from portfolios where title = 'Разработанные игры'), 'https://i.ytimg.com/vi/xw-LQwvIqpc/maxresdefault.jpg', now());

insert into posts (user_id, category_id, title, description, work_required_time, published_date)
values ((select id from users where user_name = 'Роза К.'),
        (select id from categories where  category_name = 'Разное'), 'Требуется изготовить скульптуру', 'Скульптура будет стоять перед новым построенным корпусом университета', '2024-05-05 12:00', now()),
       ((select id from users where user_name = 'Роза К.'),
        (select id from categories where  category_name = 'Спорт'), 'Ищу группу для занятий йогой', 'Хочу присоединиться к группе с хороший инструктором', '2024-01-10 12:00', now());

insert into ratings(user_id, specialist_id, rating, review_text, rating_date) values
((select id from users where user_name = 'Роза К.'), (select id from specialists where company_name = 'Art Studio Michelangelo'),
5, 'Все работы - шедевры!', now()),
((select id from users where user_name = 'Роза К.'), (select id from specialists where company_name = 'Дед Мороз и Ко'),
5, 'Очень позитивная команда', now()),
((select id from users where user_name = 'Роза К.'), (select id from specialists where company_name = 'Gaming Dev'),
5, 'Молодцы!', now()),
((select id from users where user_name = 'Qwerty'), (select id from specialists where company_name = 'Art Studio Michelangelo'),
4, 'Работает отлично, но сорвал все дедлайны.', now());

insert into responses (post_id, specialist_id, user_id, conversation_id, response, date_time) values
((select id from posts where title = 'Требуется изготовить скульптуру'),
(select id from specialists where company_name = 'Art Studio Michelangelo'), (select id from users where user_name = 'Роза К.'), '5-13', 'Здравствуйте! Я изготавливаю скульптуры. Посмотрите мой профиль.', '2023-12-14 12:00'),
((select id from posts where title = 'Требуется изготовить скульптуру'),
(select id from specialists where company_name = 'Services Co.'), (select id from users where user_name = 'Роза К.'), '5-1', 'Здравствуйте! Мой телефон 123-123-123.', '2023-12-14 13:00'),
((select id from posts where title = 'Требуется изготовить скульптуру'),
(select id from specialists where company_name = 'General Electric'), (select id from users where user_name = 'Роза К.'), '5-9', 'Здравствуйте! Мой телефон 2344-544.', '2023-12-14 14:00'),
((select id from posts where title = 'Ищу группу для занятий йогой'),
(select id from specialists where company_name = 'General Electric'), (select id from users where user_name = 'Роза К.'), '5-9', 'Йога центр - 93939-332', '2023-12-14 1:00'),
((select id from posts where title = 'Ищу группу для занятий йогой'),
(select id from specialists where company_name = 'Samsung Electronics'), (select id from users where user_name = 'Роза К.'), '5-7', 'Йога в парке каждый день в 8:00. Присоединяйтесь!', '2023-12-14 2:00'),
((select id from posts where title = 'Ищу группу для занятий йогой'),
(select id from specialists where company_name = 'Oracle Corporation'), (select id from users where user_name = 'Роза К.'), '5-6', 'Посмотрите мой профиль', '2023-12-14 2:00'),
((select id from posts where title = 'Ищу группу для занятий йогой'),
(select id from specialists where company_name = 'Boeing'), (select id from users where user_name = 'Роза К.'), '5-11', 'Посмотрите мой профиль', '2023-12-14 2:00'),
((select id from posts where title = 'Ищу группу для занятий йогой'),
(select id from specialists where company_name = 'Дед Мороз и Ко'), (select id from users where user_name = 'Роза К.'), '5-14', 'Посмотрите мой профиль', '2023-12-14 2:00');

insert into messages (sender_id, receiver_id, message_text, date_time)
values ((select id from users where user_name = 'Роза К.'), (select id from users where user_name = 'Микеланджело Буанаротти'),
'Здравствуйте! Можете отправить прайс-лист на Ваши услуги', '2023-12-15 12:00'),
((select id from users where user_name = 'Микеланджело Буанаротти'), (select id from users where user_name = 'Роза К.'),
'Здравствуйте! Перейдите в мой профиль, есть ссылка в резюме', '2023-12-15 12:05'),
((select id from users where user_name = 'Роза К.'), (select id from users where user_name = 'Микеланджело Буанаротти'),
'Хорошо, спасибо', '2023-12-15 12:10');

insert into notifications (user_id, notification_text, notification_date) values
((select id from users where user_name = 'Роза К.'), 'Поступил новый отклик на Ваш пост - Требуется изготовить скульптуру', '2023-12-14 12:00'),
((select id from users where user_name = 'Роза К.'), 'Поступил новый отклик на Ваш пост - Требуется изготовить скульптуру', '2023-12-14 13:00'),
((select id from users where user_name = 'Роза К.'), 'Поступил новый отклик на Ваш пост - Требуется изготовить скульптуру', '2023-12-14 14:00'),
((select id from users where user_name = 'Роза К.'), 'Поступил новый отклик на Ваш пост - Ищу группу для занятий йогой', '2023-12-14 1:00'),
((select id from users where user_name = 'Роза К.'), 'Поступил новый отклик на Ваш пост - Ищу группу для занятий йогой', '2023-12-14 2:00'),
((select id from users where user_name = 'Роза К.'), 'Поступил новый отклик на Ваш пост - Ищу группу для занятий йогой', '2023-12-14 2:00'),
((select id from users where user_name = 'Роза К.'), 'Поступил новый отклик на Ваш пост - Ищу группу для занятий йогой', '2023-12-14 2:00'),
((select id from users where user_name = 'Роза К.'), 'Поступил новый отклик на Ваш пост - Ищу группу для занятий йогой', '2023-12-14 2:00');

insert into subscriptions_on_tariffs(user_id, tariff_id, start_period_time, end_period_time) values
((select id from users where user_name = 'Alex'), (select id from tariffs where tariff_name = 'free'), '2023-12-01 12:00', '3000-12-01 12:00'),
((select id from users where user_name = 'Qwerty'), (select id from tariffs where tariff_name = 'quarterly'), '2023-12-01 12:00', '2024-03-01 12:00'),
((select id from users where user_name = 'JohnDoe'), (select id from tariffs where tariff_name = 'half-yearly'), '2023-12-01 12:00', '2024-06-01 12:00'),
((select id from users where user_name = 'AliceSmith'), (select id from tariffs where tariff_name = 'yearly'), '2023-12-01 12:00', '2024-12-01 12:00'),
((select id from users where user_name = 'EmilyJohnson'), (select id from tariffs where tariff_name = 'free'), '2023-12-01 12:00', '3000-12-01 12:00'),
((select id from users where user_name = 'Микеланджело Буанаротти'), (select id from tariffs where tariff_name = 'quarterly'), '2023-12-01 12:00', '2024-03-01 12:00'),
((select id from users where user_name = 'Дед Мороз'), (select id from tariffs where tariff_name = 'free'), '2023-12-01 12:00', '3000-12-01 12:00'),
((select id from users where user_name = 'Бакыт Бакытов'), (select id from tariffs where tariff_name = 'free'), '2023-12-01 12:00', '3000-12-01 12:00');

INSERT INTO contacts (user_id, contact_type, contact_value) VALUES
(1, 'phone', '+1234567890'),
(2, 'email', 'user1@example.com'),
(3, 'WhatsApp', '+9876543210'),
(4, 'tiktok', '@user2'),
(1, 'telegram', '@user3'),
(2, 'instagram', 'user4'),
(3, 'other', 'custom_contact_1'),
(4, 'phone', '+9876543210'),
(1, 'email', 'user5@example.com'),
(2, 'WhatsApp', '+1234567890'),
(5, 'phone', '+5551234567'),
(6, 'email', 'user5@example.com'),
(7, 'WhatsApp', '+5559876543'),
(8, 'tiktok', '@user6'),
(9, 'telegram', '@user7'),
(5, 'instagram', 'user8'),
(6, 'other', 'custom_contact_2'),
(7, 'phone', '+5552345678'),
(8, 'email', 'user9@example.com'),
(9, 'WhatsApp', '+5558765432'),
(10, 'phone', '+11122334455'),
(11, 'email', 'user10@example.com'),
(12, 'WhatsApp', '+11198765432'),
(13, 'tiktok', '@user11'),
(14, 'telegram', '@user12'),
(10, 'instagram', 'user13'),
(11, 'phone', '+11123456789'),
(12, 'email', 'user14@example.com'),
(13, 'WhatsApp', '+11187654321'),
(15, 'phone', '+12223334444'),
(18, 'tiktok', '@user16'),
(19, 'telegram', '@user17'),
(20, 'instagram', 'user18'),
(15, 'phone', '+12221234567'),
(16, 'email', 'user19@example.com'),
(17, 'WhatsApp', '+12228765432'),
(18, 'telegram', '@user20'),
(19, 'instagram', 'user21'),
(20, 'tiktok', '@user22'),
(15, 'WhatsApp', '+12227654321'),
(16, 'phone', '+12224567890'),
(17, 'email', 'user23@example.com'),
(18, 'instagram', 'user24'),
(19, 'tiktok', '@user25'),
(20, 'telegram', '@user26'),
(15, 'email', 'user27@example.com'),
(16, 'telegram', '@user28'),
(21, 'phone', '+13334445555'),
(22, 'email', 'user21@example.com'),
(23, 'WhatsApp', '+13339998888'),
(24, 'tiktok', '@user22'),
(25, 'telegram', '@user23'),
(26, 'instagram', 'user24'),
(27, 'phone', '+13331234567'),
(22, 'WhatsApp', '+13338887777'),
(23, 'telegram', '@user26'),
(24, 'instagram', 'user27'),
(25, 'tiktok', '@user28'),
(26, 'WhatsApp', '+13337654321'),
(27, 'phone', '+13334567890'),
(21, 'email', 'user29@example.com'),
(22, 'instagram', 'user30'),
(23, 'tiktok', '@user31'),
(24, 'telegram', '@user32'),
(25, 'email', 'user33@example.com'),
(26, 'telegram', '@user34'),
(27, 'WhatsApp', '+13336789012'),
(28, 'phone', '+14445556666'),
(29, 'email', 'user28@example.com'),
(30, 'WhatsApp', '+14441112222'),
(31, 'tiktok', '@user29'),
(32, 'telegram', '@user30'),
(33, 'instagram', 'user31'),
(34, 'phone', '+14441234567'),
(35, 'email', 'user32@example.com'),
(36, 'WhatsApp', '+14448887777'),
(28, 'telegram', '@user33'),
(29, 'instagram', 'user34'),
(30, 'tiktok', '@user35'),
(31, 'WhatsApp', '+14447654321'),
(32, 'phone', '+14444567890'),
(33, 'email', 'user36@example.com'),
(34, 'instagram', 'user37'),
(35, 'tiktok', '@user38'),
(36, 'telegram', '@user39'),
(28, 'email', 'user40@example.com'),
(29, 'telegram', '@user41'),
(37, 'phone', '+15556667777'),
(38, 'email', 'user37@example.com'),
(39, 'WhatsApp', '+15552223333'),
(40, 'tiktok', '@user38'),
(37, 'WhatsApp', '+15558887777'),
(38, 'telegram', '@user42'),
(39, 'instagram', 'user43'),
(37, 'tiktok', '@user47'),
(39, 'email', 'user49@example.com'),
(40, 'telegram', '@user50');
